export const ADD_TO_CART = "ADD_TO_CART";
export const CART_COUNT = "CART_COUNT";
export const CHANGE_QUANTITY_IN_CART = "CHANGE_QUANTITY_IN_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const GET_STRIPE_API_KEY = "GET_STRIPE_API_KEY";
