export const ALL_COUPONS_REQUEST = "ALL_COUPONS_REQUEST";
export const ALL_COUPONS_SUCCESS = "ALL_COUPONS_SUCCESS";
export const ALL_COUPONS_FAIL = "ALL_COUPONS_FAIL";
export const NEW_COUPON_REQUEST = "NEW_COUPON_REQUEST";
export const NEW_COUPON_SUCCESS = "NEW_COUPON_SUCCESS";
export const NEW_COUPON_FAIL = "NEW_COUPON_FAIL";
export const NEW_COUPON_RESET = "NEW_COUPON_RESET";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_RESET = "DELETE_COUPON_RESET";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
